name: e_music
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  go_router: ^11.1.3
  google_fonts: ^6.1.0
  just_audio: ^0.9.35
  just_audio_background: ^0.0.1-beta.10
  on_audio_query: ^2.9.0
  permission_handler: ^11.0.1
  rxdart: ^0.27.7
  wakelock: ^0.6.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
